title: Albert Luna
logo: "/images/IMG_3723.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Estoy cursando el último curso de Ingniería Multimedia y llevo más de 3 años de experiencia en el área de programación y el diseño. Busco hacer prácticas para consolidar y poner en práctica mis conocimientos en los distintos ámbitos de la multimedia. 
  <br><br>
  Estoy interesado en poder desarrollar mi carrera profesional y encontrar un trabajo que encaje con mis aspiraciones.
  <br><br>
  <a href="https://www.linkedin.com/in/albert-luna/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
